trigger:
- main   # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'drop'
    path: '$(Pipeline.Workspace)/drop'
    
- task: SSH@0
  inputs:
    sshEndpoint: 'radicalVMSC'
    runOptions: 'inline'
    inline: |
      sudo rm -rf /var/www/html/*
      sudo mkdir -p /var/www/html
      exit 0

- task: SSH@0
  inputs:
    sshEndpoint: 'radicalVMSC'
    runOptions: 'inline'
    inline: |
      echo "Uploading files..."
      sudo apt install rsync -y
      rsync -avz ./drop/ /var/www/html/
