trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    sudo apt-get update
    sudo apt-get install zip unzip
    zip -r output.zip . -x "*.git*"
  displayName: 'Create Deployment Package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'output.zip'
    artifact: 'drop'
    publishLocation: 'pipeline'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'radicalSC'  # Your service connection name
    appName: 'radicaldemoapp'       # Your Azure App Service name
    package: '$(Pipeline.Workspace)/output.zip' # Path to your zip file
  displayName: 'Deploy to Azure App Service'
